#!/usr/bin/env python3
"""Rasterise the launcher's Games (Giochi) icon into src/art/GamesIcon.h.

Stdlib only, on purpose: this repo's build box has no PIL and the glyph is
plain rectangles, so a hand-rolled rasteriser is both smaller and reviewable.

Output format is dictated by art/LauncherIcons.h and the two blitters that
consume it (LauncherScene::drawIcon, SettingsScene::renderIconStyle):
104x104, 1 bpp, MSB-first, 13 bytes per row, and **bit 0 = ink** — a byte of
0xFF is blank paper. Getting that polarity backwards yields a black tile.

The motif is a 3x3 board with a diagonal of filled cells: the one shape that
still reads as "game" after the launcher's nearest-neighbour downscale to
87 px and Settings' to 72 px, where anything thinner than 2 px can vanish.

Deterministic: re-running overwrites the header with byte-identical output.

    python3 tools/lume-games/gen_games_icon.py --out src/art/GamesIcon.h
"""

import argparse
import os
import sys

SIZE = 104
ROW_BYTES = (SIZE + 7) // 8  # 13, and also the stride both blitters assume

# Geometry. The existing packs keep their ink inside roughly x/y 9..94, so the
# new glyph uses the same optical margin instead of filling the 104 box.
PAD = 8
FRAME_R = 10  # outer corner radius; the inner edge follows at FRAME_R - THICK
FRAME_THICK = 3
LINE_THICK = 2  # internal grid lines: 2 px survives the 0.69x preview scale
CELL_INSET = 3  # paper gutter between a filled cell and the lines around it

# Board arithmetic, kept exact so no cell is a pixel wider than its siblings:
# outer 88 px (104 - 2*8), inner span 82 px (88 - 2*3), and
# 82 - 2*2 (two grid lines) = 78 = 3 * 26, so every cell is 26 px.
OUTER = SIZE - 2 * PAD
INNER0 = PAD + FRAME_THICK
INNER_SPAN = OUTER - 2 * FRAME_THICK
CELL = (INNER_SPAN - 2 * LINE_THICK) // 3

# Tic-tac-toe diagonal. Three solid cells is the brief; the diagonal is the
# arrangement that stays unambiguous at 72 px (a scattered trio reads as noise).
FILLED = ((0, 0), (1, 1), (2, 2))


def cell_origin(index):
    """Top-left pixel of board cell `index` (0..2) along either axis."""
    return INNER0 + index * (CELL + LINE_THICK)


def in_rounded_rect(x, y, x0, y0, w, h, r):
    """Membership test for a rounded rect, corners as quarter discs."""
    if not (x0 <= x < x0 + w and y0 <= y < y0 + h):
        return False
    if r <= 0:
        return True
    x1 = x0 + w - 1
    y1 = y0 + h - 1
    cx = x0 + r if x < x0 + r else (x1 - r if x > x1 - r else None)
    cy = y0 + r if y < y0 + r else (y1 - r if y > y1 - r else None)
    if cx is None or cy is None:
        return True  # on one of the four straight edges
    dx = x - cx
    dy = y - cy
    return dx * dx + dy * dy <= r * r


def rasterise():
    """Return the glyph as a list of SIZE rows of SIZE booleans (True = ink)."""
    ink = [[False] * SIZE for _ in range(SIZE)]

    # Outer frame: the ring between two concentric rounded rects.
    inner_r = FRAME_R - FRAME_THICK
    for y in range(SIZE):
        for x in range(SIZE):
            outside = in_rounded_rect(x, y, PAD, PAD, OUTER, OUTER, FRAME_R)
            hole = in_rounded_rect(x, y, INNER0, INNER0, INNER_SPAN, INNER_SPAN, inner_r)
            if outside and not hole:
                ink[y][x] = True

    # Two vertical + two horizontal internal lines -> the 3x3 board. They span
    # the full inner width so they meet the frame instead of floating.
    for i in (1, 2):
        start = cell_origin(i) - LINE_THICK
        for t in range(LINE_THICK):
            for p in range(INNER0, INNER0 + INNER_SPAN):
                ink[start + t][p] = True  # horizontal
                ink[p][start + t] = True  # vertical

    # Solid cells, inset so the grid lines stay visible alongside them.
    span = CELL - 2 * CELL_INSET
    for row, col in FILLED:
        y0 = cell_origin(row) + CELL_INSET
        x0 = cell_origin(col) + CELL_INSET
        for y in range(y0, y0 + span):
            for x in range(x0, x0 + span):
                ink[y][x] = True

    return ink


def pack(ink):
    """Pack to MSB-first rows with bit 0 = ink (paper bytes come out 0xFF)."""
    out = bytearray()
    for y in range(SIZE):
        row = bytearray(b"\xff" * ROW_BYTES)
        for x in range(SIZE):
            if ink[y][x]:
                row[x >> 3] &= ~(1 << (7 - (x & 7))) & 0xFF
        out += row
    return bytes(out)


def preview(ink):
    """Full-resolution ASCII art, one line per bitmap row."""
    return ["".join("#" if px else "." for px in row) for row in ink]


def header(data, art):
    lines = [
        "#pragma once",
        "#include <cstdint>",
        "",
        "// Generated by tools/lume-games/gen_games_icon.py — do not hand-edit.",
        "// 104x104, MSB-first, bit 0 = ink (same format as art/LauncherIcons.h,",
        "// so 0xFF bytes are blank paper). 13 bytes per row, 1352 bytes total;",
        "// one source line per bitmap row makes a bad blit obvious in review.",
        "//",
        "// A 3x3 board with a diagonal of filled cells. It has to survive two",
        "// nearest-neighbour downscales — 87 px on the launcher's 4-row grid and",
        "// 72 px in Settings' icon-style preview — which is why the frame is 3 px,",
        "// the internal lines 2 px, and the filled cells 20 px blocks.",
        "//",
        "// Preview (# = ink):",
    ]
    lines += ["// " + row for row in art]
    lines += [
        "",
        "constexpr uint8_t XPhoneIcon_games[] = {",
    ]
    for y in range(SIZE):
        row = data[y * ROW_BYTES : (y + 1) * ROW_BYTES]
        lines.append("    " + ", ".join("0x%02X" % b for b in row) + ",")
    lines += ["};", ""]
    return "\n".join(lines)


def main(argv):
    ap = argparse.ArgumentParser(description="Generate the Games launcher icon header.")
    ap.add_argument("--out", required=True, help="path of the header to write")
    args = ap.parse_args(argv)

    ink = rasterise()
    data = pack(ink)
    assert len(data) == SIZE * ROW_BYTES == 1352, len(data)
    art = preview(ink)

    for row in art:
        print(row)

    os.makedirs(os.path.dirname(os.path.abspath(args.out)), exist_ok=True)
    with open(args.out, "w", newline="\n") as f:
        f.write(header(data, art))
    print("wrote %s (%d bytes of bitmap)" % (args.out, len(data)), file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
